# Site settings
title: "My GitHub Resume"
description: "A short and sweet resume for a quick overview of my qualifications"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Simen D. Aune"
resume_title:                   "Senior Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hire@simen.foo"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+47 815 493 00"
resume_contact_address:         "Portveien 2, Sagene"

resume_header_contact_info:     "Portveien 2, Sagene • 815 493 00 • hire@simen.foo"
display_header_contact_info:    "true"

# resume_header_intro: "<p>This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but keep it brief and concise</p>"
resume_header_intro: "<p>Executive summary will arrive here shortly...</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_bluesky_url:           "https://bsky.simen.foo"
  resume_github_url:            "https://github.com/simenaun"
  # resume_twitter_url:           "http://twitter.com/"
  # resume_dribbble_url:          "https://dribbble.com/"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://resume.simen.foo"
  # resume_medium_url:            "https://medium.com/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
